export const authPermissionSeed = [
  { name: 'lorem ipsum', permission: 'empty', description: 'This permission system will be use in future' },
  // { name: 'sign up', permission: 'write:auth:sign-up', description: 'Register user' },
  // { name: 'sign in', permission: 'write:auth:sign-in', description: 'Sign in user' },
  // { name: 'sign out', permission: 'write:auth:sign-out', description: 'Sign out user' },
  // { name: 'is authenticated', permission: 'write:auth:isAuthenticated', description: 'Check user auth' },
  // { name: 'admin create', permission: 'write:auth:admin:user:create', description: 'Create admin user' },
  // { name: 'tenant create', permission: 'write:tenant:create', description: 'Create tenant' },
  // { name: 'tenant list', permission: 'read:tenant:list', description: 'List tenants' },
  // { name: 'tenant info', permission: 'read:tenant:info', description: 'Get tenant info' },
  // { name: 'tenant update', permission: 'update:tenant', description: 'Update tenant' },
  // { name: 'tenant assign', permission: 'write:tenant:assign-users', description: 'Assign users' },
  // { name: 'tenant unassign', permission: 'write:tenant:unassign-users', description: 'Unassign users' },
  // { name: 'tenant delete', permission: 'delete:tenant', description: 'Remove tenant' },
  // { name: 'tenant users', permission: 'read:tenant:users', description: 'Retrieve tenant users' },
  // { name: 'user exists', permission: 'read:tenant:userExists', description: 'Check user existence' },
  // { name: 'settings create', permission: 'write:tenantSettings:create', description: 'Create settings' },
  // { name: 'settings list', permission: 'read:settingsTenant:list', description: 'List settings' },
  // { name: 'settings info', permission: 'read:settingsTenant:info', description: 'Get settings info' },
  // { name: 'settings update', permission: 'update:settingsTenant', description: 'Update settings' },
  // { name: 'settings delete', permission: 'delete:settingsTenant', description: 'Delete settings' },
  // { name: 'user list', permission: 'read:user:list', description: 'List users' },
  // { name: 'user tenants', permission: 'read:user:tenants', description: 'Retrieve user tenants' },
  // { name: 'user delete', permission: 'delete:user', description: 'Remove user' },
];
